const GAME_PHASES = {
  WAITING: 'WAITING',
  ROLE_ASSIGNMENT: 'ROLE_ASSIGNMENT',
  SIGNAL_PHASE: 'SIGNAL_PHASE',
  VOTING_PHASE: 'VOTING_PHASE',
  RESOLUTION: 'RESOLUTION',
  NEXT_ROUND: 'NEXT_ROUND',
  END_GAME: 'END_GAME'
};

const PLAYER_ROLES = {
  SENDER: 'SENDER',
  RECEIVER: 'RECEIVER',
  UNASSIGNED: 'UNASSIGNED'
};

module.exports = {
  GAME_PHASES,
  PLAYER_ROLES
};